def get_train():
    train = [(
             "Happy Lockdown 6.0! - Drinking a Triple Tripel Straight Up by @thehowlinghound @ Bringabeeralong Holiday House",
             "pos"),
             (
             "INNR \u2014 COVID likely to lock India's women out of job market for years: Azim Premji University report finds 47 percent of women who lost jobs last year have been made permanently redundant. A woman sweeps next to the\u00a0... View article... https://t.co/WnOv8JLSpX",
             "neg"),
             (
             "Your prayers have worked again and Ad\u00e8le is getting better by the day. Thank you so much for thinking of Ad\u00e8le in her time of need. #covid #friends #love #people #europe #nuskin #family @ Billings, Montana https://t.co/5iTq6UuKcT",
             "pos"),
             (
             "So excited for this event.. come out in support me and all the other businesses coming \ud83e\udd17.\n#bakerdaves #eventcoming @ Corona, California https://t.co/sBsXKHgnfx",
             "pos"),
             (
             "Getting up at 5am to catch light wind waves with my son is simply the most amazing relief from the #coronavirus pandemic. I highly recommend it. #westonsupamare is fantastic for skim\u2026 https://t.co/q5uPiRwgEv",
             "pos"),
             (
             "Friday at the zoo. Limited visitors plus hand sanitizer, distance signs and marked restrictions everywhere they needed to be. Reassuring Covid prevention protocol work in action. @ Los Angeles Zoo and Botanical Gardens https://t.co/lIqC3zHy7T",
             "pos"),
             (
             "THEY'RE SO PRETTY!! @the.canadianpress #readytoedit #workingfromhome #newedition #saskatchewan #journalismmatters #journalism #journalist #journalismlife #journalismjobs @ Humboldt, Saskatchewan https://t.co/id6LLCXXWV",
             "pos"),
             (
             "Sooooo glad I called to see if they had leftover vaccine! I got the last one for the day. I\u2019m so grateful! #vaccinate #modernavaccice #byecovid19 @ Walgreens https://t.co/6Cy8ssxcYd",
             "pos"),
             (
             "Always great to have visitors, thanks \ud83e\udd29 for visiting Hannah and Toby love you. D2 #quarantine #quarantinelife #wellington @ Wellington, New Zealand https://t.co/WCVkGzybR5",
             "pos"),
             (
             "Thanks to everyone for the birthday wishes! Ready for this pandemic to be over so we can all celebrate, ideally packed into a small bar \ud83c\udf7b \ud83c\udf89 @ Elkins Park https://t.co/tkxj3spbQl",
             "pos"),
             (
             "Excellent #zoom  event tonight that helped us all...\n#Covid19 \n#CovidVaccine \n#BlackAndBrown Communities @ Delaware County, Pennsylvania https://t.co/sOnMa1GZdd",
             "pos"),
             (
             "So good to be back at the #gym after a 4 month lockdown. Dreamt.of the gym so this was the perfect song for the first workout. Next up @cannibalcorpseofficial of course\n#gym #gymmotivation @ Montreal, Quebec https://t.co/ZHqY84swvW",
             "pos"),
             (
             "Different but enjoyable session today. Talking with @grantthorntonie guys about all things Physio, Back Pain and working from home! #physiotherapy #ILikeToMoveItMoveIt @ The Physiotherapy Centre https://t.co/YTB1Nt2VNa",
             "pos"),
             (
             "I feel so lucky to have the opportunity to get his vaccine. This is the beginning of much needed NORMALCY. \n\nBy the way it didn't hurt. I'm just being dramatic. @ Bronx, NY https://t.co/78Y4uEx8qY",
             "pos"),
             (
             "What a great way to start my Friday! My first COVID vaccine is in the books.\n\u2022\n#fauciouchie #covid_19 #covidvacccine @ Walgreens https://t.co/jeQ0x0GOf7",
             "pos"),
        # neg
             ("A big blow to our industry again f$$k Corona @ Keron Safaris &amp; Hotels https://t.co/HsWuOvFB6C",
              "neg"),
             (
             "Learning the hard way not to push myself. Recovering from COVID-19 sucks. #covid_19 #covid19sucks #recoveryfromcovid @ Huntington Hospital https://t.co/jCaYdxJGHq",
             "neg"),
             (
             "This year really sucks... \u2009\n\u2009\n#covid #memes #cordyceps #humor #2021 #2020 #thelastofus #whereisellie @ Portland, Maine https://t.co/66QcETCB7A",
             "neg"),
             (
             "Another day of cancellations.... Covid please just disappear!!! Huge 10\u201d cakes for only \u00a345 each, delivery is available... DM \ud83d\udc8c\n-\nHappy Birthday toppers can be added! \ud83d\udc97 @ Manchester, United Kingdom https://t.co/pbNJgyTxqt",
             "neg"),
             ("The human race is doomed. https://t.co/CJBHrw1YHk", "neg"),
             (
             "How many back to school days can an 8yr old have.. This lockdown was easier and more fun so mixed emotions today. I'm gonna miss @iamjustlorcan around the house #backtoschool @ Ballymoney Wexford https://t.co/OTPRrISpdX",
             "neg"),
             (
             "Although the Covid pandemic is going down, I still spend my life cautiously #gotowork #normallife #selfie #cautious #strong @ Kew, Surrey, United Kingdom https://t.co/2X9O0fmIdB",
             "neg"),
             (
             "GO AWAY!!!!!!!!!!!!!!!!!! Just bc our governor wants to kill us, you have no excuse to vacation like it\u2019s not a pandemic. You live where it\u2019s cold. Boo hoo. #deathsantis #endspringbreak https://t.co/ugsdpCxWEt",
             "neg"),
             (
             "I miss walking in #uxbridge .. seat in my favourite places and drink good coffee.. #lockdown #waiting @ Uxbridge https://t.co/26lXkMlbb1",
             "neg"),
             (
             "This Van looks how I feel about lockdown 3.... \n\n#ineedaservice\n#vwcampervan \n#vwcamper\n#worseforwear \n#knackered @ The Compton School https://t.co/q4vUsx0Fuj",
             "neg"),
             (
             "Disgusted with the level of reporting in mainstream media over hysteria surrounding deaths of diabetics from Covid-19.\n\nYes, diabetes co-morbidity accounts for a third of deaths in hospital but without reference to\u2026 https://t.co/Tg5494ENnk",
             "neg"),
             (
             "This is my nephew. He was taken by COVID-19 today. Please say a prayer for him and his family and friends.\n#family #covidsucks #pray @ Culver City, California https://t.co/BZbW8IN7gS",
             "neg"),
             (
             "This... why aren't mainstream media reporting this... scaremongering that's why. https://t.co/wCHiwt9jLQ",
             "neg"),
             ("Vaccine wanker has arrived! #nofilter @ Sommar brewery https://t.co/FHOoHbRc1n", "neg"),
             ("Throwback to happier times....#covid19 @ Gastown https://t.co/UqGTafKZZW", "neg"),
             # POSITIVE FAKE DATA MADE BY ME
             ("Had a very nice time today at the park", 'pos'),
             ("Lovely time today with friends. It makes me happy to talk to you guys ", 'pos'),
             ("So happy to have this opportunity to work at Microsoft", 'pos'),
             ("Nothing better than reuniting with good old friends", 'pos'),
             ("I am relieved to see all my friends do well", 'pos'),
             (
             "Had great fun today at this Zoom event held to motivate people to exercise. Great work everyone!", 'pos'),
             ("There is such wonderful scenery at the Cliffs of Moher", 'pos'),
             ("This new Netflix show is so fun!! I like it a lot", 'pos'),
             ("Gorgeous views at Dublin today", 'pos'),
             ("What a cool new feature added to Call Of Duty !", 'pos'),
             ("I received amazing news today... I am going to be a dad!", 'pos'),
             (
             "Thank you Netflix for all of the great content you're putting out. I'm looking forward to more coming out!",
             'pos'),
             ("Happy Birthday Jake, let's have a big celebration of your 40 years after lockdown ends", 'pos'),
             ("I'm so lucky to have such thoughtful and kind friends. Thank you to everyone", 'pos'),
             ("This new Fortnite skin is so impressive. I LOVE it, make more amazing content like this!", 'pos'),
             # NEGATIVE FAKE DATA MADE BY ME
             ("I hate being locked down", 'neg'),
             ("Such terrible news came out today. I am so sad", 'neg'),
             ("I am so angry at people who oppose vaccination! They are bad", 'neg'),
             ("Everyone is so sad right now", 'neg'),
             ("This new update sucks! It's terrible", 'neg'),
             ("The new design is awful!", 'neg'),
             ("The mobile app is glitchy and definitely not user friendly", 'neg'),
             ("I HATE this game", 'neg'),
             ("Ranger fans are terrible!", 'neg'),
             ("Horrible comments made by the President today", 'neg'),
             ### SENTIMENT104 TWEETS
             ("@Kenichan I dived many times for the ball. Managed to save 50% The rest go out of bounds", 'neg'),
             ("my whole body feels itchy and like its on fire", 'neg'),
             ("Need a hug", 'neg'),
             ("@caregiving I couldn't bear to watch it. And I thought the UA loss was embarrassing . . . . .", 'neg'),
             ("Hollis' death scene will hurt me severely to watch on film wry is directors cut not out now?", 'neg'),
             ("this week is not going as i had hoped", 'neg'),
             ("I hate when I have to call and wake people up", 'neg'),
             ("im sad now Miss.Lilly", 'neg'),
             ("some1 hacked my account on aim now i have to make a new one", 'neg'),
             ("thought sleeping in was an option tomorrow but realizing that it now is not. evaluations in the morn..",
              'neg'),
             ("ok I'm sick and spent an hour sitting in the shower cause I was too sick to stand and held back the ...",
              'neg'),
             ("really don't feel like getting up today... but got to study to for tomorrows practical exam...", 'neg'),
             ("Sad, sad, sad. I don't know why but I hate this feeling I wanna sleep and I still can't!", 'neg'),
             ("@tea oh! i'm so sorry i didn't think about that before retweeting.", 'neg'),
             ("I have a sad feeling that Dallas is not going to show up I gotta say though, you'd think more shows...",
              'neg'),
             ("i really hate how people diss my bands! Trace is clearly NOT ugly!", 'neg'),
             (
             "wonders why someone that u like so much can make you so unhappy in a split seccond . depressed .", 'neg'),
             ("why is it always the fat ones?!", 'neg'),
             ("I'm so cold", 'neg'),
             ("my nokia 1110 died..", 'neg'),
             ("I'm stuck awake in the middle of the night for the second day in a row. And I felt terrible yesterda...",
              'neg'),
             ("Staying at a friends house...house sitting, neighbors are SO loud-having a party", 'neg'),
             ("pps.. As I said.. I still got one day remain and now problem come", 'neg'),
             ("spencer is not a good guy.", 'neg'),
             ("i hate to see the spartans so sad", 'neg'),
             ("sad that the 'feet' of my macbook just fell off", 'neg'),
             ("I LOVE @Health4UandPets u guys r the best!!", 'pos'),
             ("im meeting up with one of my besties tonight! Cant wait!! - GIRL TALK!!", 'pos'),
             ("Dancing around the room in Pjs, jamming to my ipod. Getting dizzy. Well twitter, you asked!", 'pos'),
             ("YAY! found a new cuddle buddy", 'pos'),
             ("today is our two month anniversary!!! i love you sooooooo much Diana. omg you dont even know TAR HE...",
              'pos'),
             ("Morning Tweetland, a long day ahead! Hope everyone has a great day", 'pos'),
             ("loving life... and loving you", 'pos'),
             ("@Honey3223 Lurkers now that was interesting", 'pos'),
             ("shenagians! my team is awesome&lt;3", 'pos'),
             ("just had a real good moment. i missssssssss him so much,", 'pos'),
             ("@guykawasaki congrats on 100,000 followers. Wow almost 4 times of what I have", 'pos'),
             ("@amandahesser thanks! i couldn't have done it without you", 'pos'),
             ("Just spoke with my fam in #Japan via #Skype! Love to see my little 16-mo-old nephew growing!", 'pos'),
             ("A friend feels like a beer on a Monday night. That's never good. But beer is always good. Always.",
              'pos'),
             ("@JonathanRKnight : agreed. internet? random. but i like random. watched dirty dancing, great movie, ...",
              'pos'),
             ("@JonathanRKnight Oh its real Jon! We all r so excited that u and the guys came back 4 us. We appre...",
              'pos'),
             ("@ijustine the gym is an awesome place! work it out", 'pos'),
             ("@keyannaaa the new story of your life will include magic fountain with me", 'pos'),
             ("@Lyndeeezy hahah not yet! but soon. very soon", 'pos'),
             ("I am gonna help my mom get a twitter", 'pos'),
             ("@rhonda_brown thanks for the tip on Sam's Club!", 'pos'),
             ("just got home from Neil's. watched Nick &amp; Nora's Playlist... pretty funny", 'pos'),
             ("and now off to bed after an amazing night chatting with a pretty amazing guy ( you know who you are...",
              'pos'),
             ("the cars in Fast and Furious get me excited", 'pos'),
             ("I'm melting. *sighs* Serendipity is such a sweet sweet movie. I love it.", 'pos'),
             ("Dodgers beat the Padres Go Blue!", 'pos'),
             ("michigan state you make me sad", 'neg'),
             ("omg. my mouth is in so much pain i just wanna sleep untill its time to take my braces off.", 'neg'),
             ("@hyperbets i hope this doesn't last too long. i feel miserable!", 'neg'),
             ("@cococourtney i was just listening to the sweets for the first time in forever! i miss them so much ...",
              'neg'),
             ("Wow. The most depressing thing in the world is losing a video that you've created in a matter of sec...",
              'neg'),
             ("today sucked. I'm gonna die without chris and callum! wahhh!", 'neg'),
             ("HELP! I need a new boyfriend... I'm stuck in a rut", 'neg'),
             ("I feel like a complete idiot. I'm the only one who doesn't get how this shit works help me", 'neg'),
             ("@Steve_Buscemi the weather in Canada is freezing", 'neg'),
             ("anyone who reads this pray for my Grandma. She's in pain", 'neg'),
             ("ITS NOT ENOUGH TO SAY THAT I MISS U", 'neg'),
             ("I'm so upset that I missed my chat and quiz online because my free internet has ceased", 'neg'),
             ("stuck at home", 'neg'),
             ("If he doesn't get better in a few days, he could have something lodged in his belly", 'neg'),
             ("the angel is going to miss the athlete this weekend", 'neg'),
             ("Grr i want to keep reading but if i do i wont have anything left to read", 'neg'),
             ("@RumLover No! u supposed to be my date", 'neg'),
             ("Crap. I need more dresses too.", 'neg'),
             ("I wanna be in a punk rock band again", 'neg'),
             ("@Brodhe geez ur no fun are you", 'neg'),
             ("@cleders sorry...i was rooting for them too...", 'neg'),
             ("Why is that when you have time off from work you get sick?", 'neg'),
             ("Death is peaceful, life however, bites", 'neg'),
             ("@nicolerichie I cried so hard when Matthew died", 'neg'),
             ("watching old videos of dance team and such... makes me miss it", 'neg'),
             ("@carlyw66 HAHA. I cried... I guess he did....", 'neg'),
             ("Is glad the Angels won their first game of the season.", 'pos'),
             ("@misstoriblack I have absolutely no doubt that I will! here's to your continued success", 'pos'),
             ("@JonathanRKnight Don't worry about it, we are just happy to have you on here!", 'pos'),
             ("had a really good day off to do some shoppping", 'pos'),
             ("@kamy775 ok..I did it...hope it works now", 'pos'),
             ("Is hella excited cuz the Italian is here", 'pos'),
             ("@HuntersMama1985 LOL, I was thinking the same thing", 'pos'),
             ("i'm feeling somewhat artistic...time to break out the sketching pad, i feel a new dress design comin...",
              'pos'),
             ("This latest episode of NewNowNext is like full of awesome!", 'pos'),
             ("aww dont make me blush!", 'pos'),
             ("Happy Morning, la toat? lumea!", 'pos'),
             ("Denise, I love you.", 'pos'),
             ("@aaminahh I'm excited about the books you received too!", 'pos'),
             ("Just bought a car!!! YAY for me!", 'pos'),
             ("Yess! Twittering from my phone again!", 'pos'),
             ("@warp I love that Aussie cattle dog story", 'pos'),
             ("@noarmsjames my lovely man is cooking me dinner and then we're going for a walk", 'pos'),
             ("@DonnieWahlberg you make me smile", 'pos'),
             ("I'm new and lost", 'pos'),
             ("I loved today", 'pos'),
             ("yeah guys i will totally bring dublin to the party. he would love the company.", 'pos'),
             ("@chasepino I wish I was as cool as you.", 'pos'),
             ("@nicolerichie that was my favorite show/series when i was little!", 'pos'),
             ("@wmmarc great interview! Glad to see it", 'pos'),
             ("@spencerordonez although we have lot work to do and cannot wait to start this project", 'pos'),
             ("ugh horrible ending to the sandra kantu story prayers go out.", 'neg'),
             ("is really sad and doesn't really know y!!??!!!", 'neg'),
             ("finding it really hard to use twitter", 'neg'),
             ("wants to cry", 'neg'),
             ("I need to go to the bank tomorrow before I go broke...", 'neg'),
             ("has hurt her ankle!! and is going to the dr", 'neg'),
             ("Photoshop, I hate it when you crash", 'neg'),
             ("vacations makes me feel sick!", 'neg'),
             ("I don't want to wake up early tomorrow. Damn you, work!", 'neg'),
             ("@stephenkruiser i had 2 put my dog down today too someone ran her over", 'neg'),
             ("@stephenkruiser I am so sorry to hear that! Take care!", 'neg'),
             ("I so hate homeworks -.- My head hurts so bad", 'neg'),
             ("sad day: manu out for the season", 'neg'),
             ("im sooo sad right now i need a hug", 'neg'),
             ("I'm tired. I feel like crap. And the world feels all crummy", 'neg'),
             ("Spring break is here at last, but no one is here to celebrate", 'neg'),
             ("@stephenkruiser that's horrible sorry to hear that.", 'neg'),
             ("not feeling v good abt myself", 'neg'),
             ("@d_castillo ugh, that's disconcerting", 'neg'),
             ("I hate converting movies just to put em on my itouch", 'neg'),
             ("im so tired of work...i need a life....", 'neg'),
             ("A little sad", 'neg'),
             ("@stephenkruiser awww so sad!!! I'm so sorry!!", 'neg'),
             ("I just can't spell today, i totally suck", 'neg'),
             ("The internet is hating me", 'neg'),
             ("people amaze me", 'pos'),
             ("now I'm happy", 'pos'),
             ("Today was so great. My roommate and I played some soccer and I also got a nice run in on this sunny...",
              'pos'),
             ("I think im in love", 'pos'),
             ("Mmmmmm shower and cozy bed. Soooo nice after this long day", 'pos'),
             ("Thanks to my new followers!", 'pos'),
             ("to a great day! Being brave pays off. Thank you Jesus-seriously.", 'pos'),
             ("I'm going so good without myspace, msn and stuff", 'pos'),
             ("@mrskutcher ur awesome", 'pos'),
             ("@adeline_sky that sounds fantastic! You're amazing! We need to watch some Muse gigs too!", 'pos'),
             ("@Eeoor - My pleasure", 'pos'),
             ("i love my grandma", 'pos'),
             ("Had a great night..really enjoying life", 'pos'),
             ("@danthedaddy I love that you. Love You, Forever.", 'pos'),
             ("Good night and good day twitters!", 'pos'),
             ("@KennethReitz yes its really awsome!", 'pos'),
             ("I love LUSH products......they're products smell and feel so good", 'pos'),
             ("Hi @DaveJMatthews ! Greeting from Poland, love your music", 'pos'),
             ("Really enjoying my DSi.", 'pos'),
             ("I like saving money", 'pos'),
             ("picked up my new car this morning", 'pos'),
             ("I love you best", 'pos'),
             ("ok, it's officially my birthday! crack a beer if you got one, that's what I'm doing", 'pos'),
             ("I'm excited for rescue me to start tomorrow. Or is it today.", 'pos'),
             ("Morning - how nice to see everyone is awake and chirp - it helps", 'pos'),
             ("too cold and tired to write good twitter.total disappointment", 'neg'),
             ("my heart has been broken.", 'neg'),
             ("looks like i've missed out on yet another job someone please employ me!", 'neg'),
             ("I'am bored. Nothing to do!", 'neg'),
             ("Errrggggg! My tummy hurts.", 'neg'),
             ("poor mel. Feeling your pain.", 'neg'),
             ("bored and lonely", 'neg'),
             ("im so tired this morning and there was only cold shower water!not happy", 'neg'),
             ("Worst burn of my life! so sick", 'neg'),
             ("Where has all my money gone?!", 'neg'),
             ("OMG, more than 360 people is the death toll in Italy", 'neg'),
             ("@SCC_Skwerl Aww how depressing!", 'neg'),
             ("@ThisismyiQ layin down...i dont feel well", 'neg'),
             ("i miss my bcd friends", 'neg'),
             ("I'm in pain", 'neg'),
             ("I can't believe it. I got my answer and didn't have to ask the question. This feels awful.", 'neg'),
             ("wow! i got sick out of nowhere and now i cant think straight....and mtv hasnt posted the hills onli...",
              'neg'),
             ("poor Sandra Cantu. My heart goes out to her family and friends. Rest in Peace Little One!", 'neg'),
             ("is very disappointed.", 'neg'),
             ("I wish I had someone to talk to. I'm so upset. no one likes me anyway", 'neg'),
             ("@honeyortar the hinge broke it works, just doesn't open smoothly and it's pissing me off. I dunno I...",
              'neg'),
             ("i don't wanna go to work i wanna go to bed!", 'neg'),
             ("i cant sleep", 'neg'),
             ("Lonely bed, no husband.", 'neg'),
             ("my birthday today. feel so old", 'neg'),
             ("I feel so great for starting twitter at suzanne but still hardly anyone has it.", 'pos'),
             ("@sweetlocs definitely a GOOD 1!", 'pos'),
             ("@WallyDWallower I love cold pizza for b'fast! Mmm!", 'pos'),
             ("It's a beautiful day...", 'pos'),
             ("Finished my book-onto #4 now", 'pos'),
             ("@Willie_Day26 i love you willie!", 'pos'),
             ("today was super fun and we tried new things plus we have future hangout buddies", 'pos'),
             ("@The_Apprentice_ come on down buddy. would love to have ya", 'pos'),
             ("i just cut my hair and it actually looks a lot better ahaha", 'pos'),
             ("@ukdivorce - Just reading your blog, looks cool!", 'pos'),
             ("glad to see you here!", 'pos'),
             ("Thanks @macheist - That was a good deal", 'pos'),
             ("omg dougie replied to me. gosh i'm so happy", 'pos'),
             ("gonna help with kids outreach this friday! whee!", 'pos'),
             ("so excited for my eye exam tomorrow.", 'pos'),
             ("it's unbelievable, but I somehow managed to write the whole standalone", 'pos'),
             ("@DDGriffith I am truly honoured", 'pos'),
             ("hope tomorrow is a nice day", 'pos'),
             ("I'm so glad you're feeling better *hugs*", 'pos'),
             ("Can't wait for tomorrow", 'pos'),
             ("I love my toothpaste.", 'pos'),
             ("enjoying the nice weather", 'pos'),
             ("It's great to know to be in your thoughts!!and...yes..we are lucky.", 'pos'),
             ("Just getting ready for work oh joy is me! Roll on holiday", 'pos'),
             ("can't wait to see cody wednesday i love my boyfriend", 'pos'),
             ("is extremely hungry", 'neg'),
             ("DAMN- my PC has COMPLETELY given out this sucks ...", 'neg'),
             ("Still feel feckin arseholed...a sign of old age me thinks", 'neg'),
             ("@sunky being a grown up is horrid, isn't it", 'neg'),
             ("Going to sleep now. Johnny just died on the OC.", 'neg'),
             ("i think i'm getting sick.", 'neg'),
             ("I cant sleep. Missing the person I love most for the past 7yrs of my life.", 'neg'),
             ("is sad because there was another earthquake in italy..", 'neg'),
             ("I stayed up too late. Didn't get the design done like I wanted to", 'neg'),
             ("JUST realized im talking to no one..", 'neg'),
             ("i hurt my leg!", 'neg'),
             ("Okay I'm sorry that was mean. I'm not nice", 'neg'),
             ("i feel lonely today....", 'neg'),
             ("there is no way i can go to school today im way too sick", 'neg'),
             ("I'm SO tired but can't sleep", 'neg'),
             ("The first serial about my city so stupid...", 'neg'),
             ("think im an insomniac, i just cant sleep..", 'neg'),
             ("feeling ill and sorry for myself", 'neg'),
             ("gloomy weather...again", 'neg'),
             ("is missing her too and totally ready to be over this stupid sickness", 'neg'),
             ("is wishing he loved me", 'neg'),
             ("finished making chocolates and feet really hurt", 'neg'),
             ("I'm sorry. I've ruined everything between us. forgive me?", 'neg'),
             ("Hmm.. The work is not easy. Wasted two hours for a silly mistake. Now one system is too slow", 'neg'),
             ("Annoying place. 4pm and half the hawker's closed", 'neg'),
             ("Had such a good time tonight...it was needed...thanks sistahs!", 'pos'),
             ("Just had a fabulous day at disney land", 'pos'),
             ("Happy Birthday my dear Love", 'pos'),
             (
             "@bloghamptons that was an great story. I remember last year that someone did that at a starbucks", 'pos'),
             ("I heard is your birthday today? Congratulations Happy Birthday! Hope you have a great day.", 'pos'),
             ("Hope ur having a great night hun n that ur feeling better.", 'pos'),
             ("aww..stop it.... u know i love ya", 'pos'),
             ("i love annie willatt passionatley with a portia salad on the side", 'pos'),
             ("@UtopiaArmoury Bedtime at 4am!! LOL Get some rest!! It's great to have you on board!", 'pos'),
             ("My macro objective is amazing.", 'pos'),
             ("250 miles from home and its nice and sunny", 'pos'),
             ("is glad for today and wishing the best for his love", 'pos'),
             ("@KingArlen come and visit Australia", 'pos'),
             ("motown is ALWAYS a good choice", 'pos'),
             ("the new afl ad gets me so excited for footy season", 'pos'),
             ("@pibby the video is perfect! Thanks again, talk to you soon", 'pos'),
             ("@KrisAllenmusic bad shape? wuts wrong? u look greattt! n good luck for tomorrw! cant wait", 'pos'),
             ("@BleedingChaos I'm doing ok hun, quite good actually. And yes, you're amazing. XX", 'pos'),
             ("@fogbugz i'd love to see a Fogbugz iPhone or Android app. Kiwi icon on your phone", 'pos'),
             ("Its as easy as breathing.", 'pos'),
             ("I am no1 Auntie today So, that means dragging Adam around the park all day :p", 'pos'),
             ("i had such a wonderfull time out with Mela last night watching DGoody 1978 play Live Keys for Rap Gr...",
              'pos'),
             ("Another day of gaming lies ahead. I love having a week off", 'pos'),
             ("has just had a bit of good news - what a wonderful start to the day", 'pos'),
             ("I'm very excited (and scared) about tomorrow. It's going to be great day", 'pos')
             ]
    return train

def get_test():
    test = [("Great day of catching up with dear friends I haven\u2019t seen since b4 these strange crazy pandemic times \ud83d\udc9c\n\n#postpandemictimes \n#jw @ Zelda's Restaurant-Capitola https://t.co/6CGrPCyxFB", 'pos'),
        ("The Saddest News Of The Decade...!!!!\ud83e\udd7a\nShri Milkha Singh Just Passed Away At The Age Of 91 Due To Covid 19 ..\ud83d\ude4f\ud83c\udffc\nRIP To The Olympic Hero Of India..\ud83d\ude22\nMay Your Sole Rest In Peace Sir..\ud83d\ude4f\ud83c\udffc\n\n#TheAmateurBong https://t.co/ycetcfdJKN",'neg'),
        ("This some real Bull \ud83d\udca9 don't make me move back to Texas where Vaccine Passports are banned. @ Los Angeles, California https://t.co/XDL7S6vs9Q", 'neg'),
        ("So grateful to everyone who made this happen! \ud83d\ude42\ud83d\udc4d\n.\n.\n.\n.\n.\n.\n.\n.\n.\n.\n#OneAccenture #We4Vaccine #Vaccination #COVID_19 @ Accenture, Magarpatta City, Pune https://t.co/Mz1scHmCsP", 'pos'),
        ("You can't see it, but I'm wearing the biggest smile \ud83d\udc89. \n\n#Sinovac #1stDoseDone #COVID19 @ Kuala Lumpur, Malaysia https://t.co/m08GIx70F8", 'pos'),
        ("How Covid-19 fucked me up and today I am again at where I was ..lost all muscles, lost the 6 packs abs. #memories2019 \nWish I could go back to being lean and mean.. once again. @ Pune, Maharashtra https://t.co/t50q8smqLh", 'neg'),
        ("Fuck COVID-19 \ud83d\udc4a\ud83d\udc4a\ud83d\udc4a\ud83e\uddbe\n\nVaccinated. #covid_19 #fuckcovid19 @ Miami, Florida https://t.co/SSvIZYvol6","neg"),
        ("My brother and I took my dad out for dinner for the first time since the pandemic started. It was so nice to finally see my dad after a long year. #\u0262\u1d07\u1d1b\u1d20\u1d00\u1d04\u1d04\u026a\u0274\u1d00\u1d1b\u1d07\u1d05 @ Ke'e Grill https://t.co/6e9lOrM3KL","pos"),
        ("This is crazy.  First COVID now Gas Prices!!! @ Florence, South Carolina https://t.co/hliwmzpVgT","neg"),
        ("Celebrating being back after another lockdown with this beauty! \ud83e\udde1 @ Emma Frances Hair https://t.co/Easvp9M4Vr","pos"),
        ("Finally got to hug my Mom after over a year of social distancing! Yay! #ilovemymomanddad @ Roseville, California https://t.co/cel0jJ7vWL","pos"),
        ("The biggest thing I have missed because of Covid 19. Football with @christopherwilliams308 @ Sutton United F.C. https://t.co/tpSynbfT8F","neg"),
        ("Gorgeous sunset tonight while out grabbing dinner!! #SoCal #Sunset #Corona @ Subway https://t.co/w81i5MNQeJ","pos"),
        ("The former guy only cares for himself https://t.co/bly2njXRuL","neg"),
        ("LOVE THIS!!! #itsallcomingback #itswhatwedo #covid_19 @ Funkbox Productions https://t.co/CofmRJe9xW","pos"),
        ("Watching these pictures now makes me feel as if it was a hundred years ago. My personal remedy from the lockdown stressed mood. \ud83c\uddeb\ud83c\uddf7 \n#paris #france #theeiffeltower #memories #throwbackmonday (Tour Eiffel): https://t.co/0f7mgPMC4U","neg"),
        #FAKE TEST DATA MADE BY ME:
        ("This pandemic is such a scam! Down with the government!","neg"),
        ("I hate these restrictions, I feel like my time is being wasted", "neg"),
        ("Love to see people finding ways to stay connected, we'll get through this together!", "pos"),
        ("So happy to have visited my sister, I hadn't seen her in 3 months. Love you sis", "pos"),
        ("I am disgusted at people not wearing masks, our hospitals are full, do your part!", "neg"),
        ("I hate how Nike charges over 100$ for any popular sneaker", "neg"),
        ("What an awful show keeping up with the Kardashains is... We need better TV", "neg"),
        ("Many Thanks to the @Nike family for the gift. Looking forward to future collaborations with you guys", "pos"),
        ("Proud to be nominated for this award amongst so many other great competitors", "pos"),
        ("Had an mazing experience today at Tayto Park. The rides are so exciting and the kids loved it! I recommended to anyone planning a day out", "pos"),
        ("The food at McDonalds is disgusting... Im never eating there again", 'neg'),
        ("Our president is pathetic. We NEED new elections", 'neg'),
        ("Our president is the best we have ever had", 'pos'),
        ("Life at Riyadh is excellent. Everything is luxurious", 'pos'),
        ("Our country is in an awful state", 'neg'),
        ("We need help. Our country is destroyed", 'neg'),
        ("My greatest success up to has been my resilience. Lets all keep going", 'pos'),
        ("Stay strong people! You are tougher than you think", 'pos'),
        ("Peace and Love to everyone! Let's unite and be in harmony", 'pos'),
        #SENTIMENT104 DATA
        ("Officially in love with true blood. Someone buy me the season?", 'pos'),
        ("@leslielehner WOOO HOO!! Happy Birthday!!!!", 'pos'),
        ("Going clubbing with my cousin! Im gonna have FUN tonight", 'pos'),
        ("Not sure what illness I have so am drinking my favorite medicine", 'pos'),
        ("@mrphanman it looks cute.", 'pos'),
        ("Thanks my friend! Good luck with puddles the scaredy pooch ", 'pos'),
        ("I knew you would do great.  hopefully next time, you won't doubt how much faith i have in you  I'm proud of u. ILYTD", 'pos'),
        ("lol.  thanks.  It making your night makes my night too", 'pos'),
        ("Dinner with my family...perfect", 'pos'),
        ("Wow... I luv it... They did an excellent Job!!!  Very cool.", 'pos'),
        ("@aantaki do you love me?!? I think you do!", 'pos'),
        ("got a beautiful Anya Hindmarch bag today at Short Hills mall, I love it", 'pos'),
        ("what a lovely day - new job, concert and now for sleep. good night, sweet dreams! ", 'pos'),
        ("Well, that was a good movie.", 'pos'),
        ("p.s. Don't forget to be awesome", 'pos'),
        ("Pretty funny exchange of words between jordan and kbraun...haha...why dont you both drink some liquid soap? lol", 'pos'),
        ("I'm feeling good about trivia tonight.", 'pos'),
        ("Had a great sleep! The foxes found somewhere else to play their dirty games. This is going to be a good day, Apprentice later", 'pos'),
        ("an amazing day start to finish. filled with my people, nature, food and friendship. a little teaching to end with, and GOODNIGHTNOW!", 'pos'),
        ("You are looking good tonight Bev, looks like you got a nice tan at the beach, so good to have you back", 'pos'),
        ("Will Ferrell always brings the LOLs", 'pos'),
        ("I love me some Conan, so I want him to do well!", 'pos'),
        ("bed time. thank you babe for everything  i love you", 'pos'),
        ("Aw my friends relationship thing is so cute. Im so happy for them.", 'pos'),
        ("@kenji6787 well I'm glad the ending was actually good", 'pos'),
        ("stressing about my recital...ugh, i dont think i can do it! ", 'neg'),
        ("Damned antismoking psa w/little boy has me so sad... pls cheer me up!", 'neg'),
        ("oh no i lost some followers where do you go...", 'neg'),
        ("Apparently I am cursed to not have free ringtones. ", 'neg'),
        ("heading for home, sick", 'neg'),
        ("Oww... hurtie lump on eye ball is hurty! ", 'neg'),
        ("Feeling crazy allergic to something lately. It's no fun, and it doesn't make mornings any easier", 'neg'),
        ("Got a big headache and don't feel too well.", 'neg'),
        ("has a cold and is working... I sad...", 'neg'),
        ("is new to this madness..and sick of the library ", 'neg'),
        ("i really miss my soulmate ", 'neg'),
        ("im so friggin bored, why cant i jus have something to do!", 'neg'),
        ("@Peppersantblai Weather sucks, really ", 'neg'),
        ("Still sad because Jake Owen did not beat Julian Hough at ACM awards", 'neg'),
        ("it hurts to smile", 'neg'),
        ("I had a panic attack because of Metallica.", 'neg'),
        ("My littlebrother just got home! I miss him when I'm not here.", 'neg'),
        ("this feels like the week from hell.....", 'neg'),
        ("is chilling out after a very painful dentist appointment ", 'neg'),
        ("Lost a follower, thats just upsetting", 'neg'),
        ("i feel like i've been stabbed in the stomach", 'neg'),
        ("I'm sick and broken hearted not a good mix!", 'neg'),
        ("I am so mad that I am missing University Day today because of my stupid internship", 'neg'),
        ("In the stupid library ", 'neg'),
        ("I wish I could do that...unfortunately, it's at work where I need mine", 'neg'),

        ("I love driving this truck  and glad that my day got a little better", 'pos'),
        ("so glad June is here... great things are happening this month, I can feel it!  now... it's time for bed", 'pos'),
        ("@JennMarieee and ur enjoying it! .. i cant wait to hear all about it .. someday!  haha .. love u!", 'pos'),
        ("@ajmclean_team Yay! I got a shoutout!  xoxo", 'pos'),
        ("awww nice guys who hold doors open do still exist!", 'pos'),
        ("you girls are so pretty. i love your guys' dresses", 'pos'),
        ("@mileycyrus you are going to love Georgia!", 'pos'),
        ("is hanging out with some really cool people &amp; having an unofficial house party.. yay for wine.", 'pos'),
        (" You moved back?  I thought Arkansas was going to be permanent.  I'm glad that you made it safe.", 'pos'),
        ("i think im in a good place... and i like that...", 'pos'),
        ("praise the Lord for very best friends! just picked mine up from the airport.", 'pos'),
        ("First Temeraire book was *amazing*. ask me about my casting of the characters in my head. but now, bed.", 'pos'),
        ("@ashleyaponte have fun tonight. Tell Amanda and Jess Hi and I love all three of ya", 'pos'),
        ("oh my bed is so freakin' awesome, it's not even funny!", 'pos'),
        ("So today didn't go as planned, but it was alright. I played games with my cousin, and finished my spanish logs  Can't wait till Wednesday", 'pos'),
        ("band concert went good  time for bed soon. gonna be hot again", 'pos'),
        ("Found it!  I am happy", 'pos'),
        ("21 years out of school and I am solving math problems on Yahoo Answers. This has got to be good for my aging brain!", 'pos'),
        ("sorten muld makes my heart light.", 'pos'),
        ("Dear God, please let it rain tomorrow so I can wear my cute ass rainboots. Thanks and Goodnight.", 'pos'),
        ("@eva_diva  I think you'll really like it.  The first 5 minutes were better than the entirety of some movies.", 'pos'),
        ("This summer will be great, i can feel it", 'pos'),
        ("nite nite tweets, until tomorrow.  sweet dreams", 'pos'),
        ("I think it's funny how clever you think you are", 'pos'),
        ("Tons of fun with Kat tonight.", 'pos'),

        ("im finally awake but i don't feel soo good ", 'neg'),
        ("So broke hate not having money", 'neg'),
        ("I hate it when i think of something to do and just as i'm about to do it, i forget wht i was gonna do", 'neg'),
        ("I'm a problem that'll never ever be solved", 'neg'),
        ("maybe that coffee wasn't a good idea", 'neg'),
        ("Woke up this morning and my throat is soooo sore. I still have to go out in the cold air", 'neg'),
        ("my little baby is sick today... sad face", 'neg'),
        ("It's gonna be a long agonizing Tuesday.", 'neg'),
        ("Monkey just woke up. She must not be feeling well. She also wet her sheet", 'neg'),
        ("anyone reply! this is going so wrong", 'neg'),
        ("@jwmayer06 Sorry we missed your bday bash!!!!", 'neg'),
        ("Snow really reallly sucks and today keeps getting worse", 'neg'),
        ("Wtf i still not feel good", 'neg'),
        ("is feeling old today.", 'neg'),
        ("dissertation and it is hatefull", 'neg'),
        ("I love the sun!! I hate school that keeps me out of the sun", 'neg'),
        ("is having another crappy day", 'neg'),
        ("that hurt my feelings *B-Unit*", 'neg'),
        ("i am tired...i dont want to be here...9 hrs left", 'neg'),
        ("My poor mother country of Italy.", 'neg'),
        ("desperate times call for desperate measures. record high of car break-ins in", 'neg'),
        ("my butt hurts.", 'neg'),
        ("Sad! Chris has to work on Easter", 'neg'),
        ("not a good day But trying to keep positive... The weekend is not THAT far.", 'neg'),
        ("staying away from tea all day today", 'neg')
    ]


    return test